#pragma once

#ifndef SHADERENGINE_ENABLE_PHASE_TELEMETRY
#define SHADERENGINE_ENABLE_PHASE_TELEMETRY 0
#endif

#ifndef SHADERENGINE_ENABLE_SHADOW_TELEMETRY
#define SHADERENGINE_ENABLE_SHADOW_TELEMETRY 0
#endif
